apiVersion: apps/v1
kind: Deployment
metadata:
  name: fulfillment
  labels:
    app: fulfillment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fulfillment
  template:
    metadata:
      labels:
        app: fulfillment
    spec:
      containers:
      - name: fulfillment
        image: cfe84/bounce
        ports:
        - containerPort: 8080
        env:
        - name: BOUNCE_COMMAND
          value: "-p '/api/fulfillment-order' -r 'Order has been fulfilled' -H 'content-type: text/plain'"
      - name: auth-facade
        image: cfe84/auth-facade
        ports:
        - containerPort: 8001
        env:
        - name: PROXY_TO
          value: "http://localhost:8080"
        - name: AUDIENCE
          value: "aud:fulfillment-service"
---

kind: Service
apiVersion: v1
metadata:
  name: fulfillment-service
spec:
  selector:
    app: fulfillment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8001
  type: LoadBalancer