apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: cfe84/bounce
        ports:
        - containerPort: 8080
        env:
        - name: BOUNCE_COMMAND
          value: "-p '/api/order' -x http://127.0.0.1:8041/api/fulfillment-order -g '/ping' -r 'PONG'"
      - name: auth-facade
        image: cfe84/auth-facade
        ports:
        - containerPort: 8001
        env:
        - name: PROXY_TO
          value: "http://localhost:8080"
        - name: AUDIENCE
          value: "aud:order-service"
      - name: ambassador-to-fulfillment
        image: cfe84/auth-ambassador
        ports:
        - containerPort: 8041
        env:
        - name: PORT
          value: "8041"
        - name: "AUTHORIZATION_URL"
          value: "http://10.0.168.219:80/oauth2/v2.0/token"
        - name: AUDIENCE
          value: "aud:fulfillment-service"
        - name: CLIENT_ID
          value: "order-service"
        - name: CLIENT_SECRET
          value: "1234"
        - name: PROXY_TO
          value: "http://10.0.98.202:80"

---

kind: Service
apiVersion: v1
metadata:
  name: order-service
spec:
  selector:
    app: order
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8001
  type: LoadBalancer